GoalingApp/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :goalings, only: [:create, :update, :destroy]
end

GoalingApp/app/models/goaling.rb
class Goaling < ActiveRecord::Base
  validates :user_id, :title, presence: true
  validates :private_public, inclusion: %w(private public)
  validates :completion, inclusion: %w(incomplete complete)

  belongs_to :user

end

GoalingApp/app/models/user.rb
class User < ActiveRecord::Base

  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  validates :username, uniqueness: true

  attr_reader :password

  after_initialize :ensure_session_token

  has_many :goals, class_name: "Goaling"

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest) == password
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def reset_session_token
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def self.generate_session_token
    SecureRandom.base64
  end

  def self.find_by_credentials(username, password)
    @user = User.find_by(username: username)
    @user && @user.is_password?(password) ? @user : nil
  end
end

GoalingApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def log_in(user)
    @current_user = user
    session[:session_token] = user.reset_session_token
  end

  def log_out
    current_user.reset_session_token
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end
end

GoalingApp/app/controllers/goalings_controller.rb
class GoalingsController < ApplicationController
  def create
    @goal = Goaling.new(goal_params)
    @goal.user_id = current_user.id
    @goal.save
    flash[:errors] = @goal.errors.full_messages
    redirect_to user_url(current_user)
  end

  def update

  end

  def destroy

  end


  private
  def goal_params
    params.require(:goal).permit(:private_public, :title, :completion)
  end
end

GoalingApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user
      log_in(@user)
      redirect_to user_url(@user.id)
    else
      flash.now[:errors] = "Invalid login credentials"
      render :new
    end
  end

  def destroy
    log_out
    render :new
  end


end

GoalingApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to user_url(@user.id)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @goals = @user.goals
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:password, :username)
  end
end

GoalingApp/app/helpers/application_helper.rb
module ApplicationHelper
end

GoalingApp/app/helpers/goalings_helper.rb
module GoalingsHelper
end

GoalingApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

GoalingApp/app/helpers/users_helper.rb
module UsersHelper
end

GoalingApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalingApp</title>

  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
  <%= button_to "Log Out", session_url, method: :delete %>
<% else %>
  <%= link_to "Log In", new_session_url%>
  <%= link_to "Sign Up", new_user_url %>
<% end %>

<%= yield %>

</body>
</html>

GoalingApp/app/views/users/new.html.erb
<h1>Create New User</h1>

<form  action= "<%= users_url%>" method="post">
  <input type="hidden" name="authenticity_token" value= "<%=form_authenticity_token%>">

  <label for="Username">
    Username
    <input type="text" name="user[username]" value="">
  </label>

  <label for="Password">
    Password
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" name="name" value="Create User">
</form>

GoalingApp/app/views/users/show.html.erb
<%= @user.username %>

<ul>Goals
  <% @goals.each do |goal| %>
    <li>
      <%= goal.title %>
      <%= button_to "Edit", goaling_url, method: :patch  %>
    </li>
  <% end %>
</ul>
<br>
New Goal
<br>
<form action="<%=goalings_url%>" method="post">
  <input type="hidden" name="authenticity_token" value= "<%=form_authenticity_token%>">

  <label for="Goal">Goal
    <input type="text" name="goal[title]" value="">
  </label>

  <input type="submit" value="New Goal">
</form>